In [3]:
import numpy as np

In [4]:
x = np.array([3,4,5])
y = np.array([4,9,7])

In [5]:
x+y

array([ 7, 13, 12])

In [7]:
x = np.array([[1,2],[3,4]])

In [13]:
x

array([[1, 2],
       [3, 4]])

In [14]:
x.ndim?

Type:        int
String form: 2
Docstring:  
int([x]) -> integer
int(x, base=10) -> integer

Convert a number or string to an integer, or return 0 if no arguments
are given.  If x is a number, return x.__int__().  For floating point
numbers, this truncates towards zero.

If x is not a number or if base is given, then x must be a string,
bytes, or bytearray instance representing an integer literal in the
given base.  The literal can be preceded by '+' or '-' and be surrounded
by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
Base 0 means to interpret the base from the string as an integer literal.
>>> int('0b100', base=0)
4

In [15]:
x.shape?

Type:        tuple
String form: (2, 2)
Length:      2
Docstring:  
Built-in immutable sequence.

If no argument is given, the constructor returns an empty tuple.
If iterable is specified the tuple is initialized from iterable's items.

If the argument is a tuple, the return value is the same object.

In [16]:
x.shape

(2, 2)

In [17]:
x.sum()

10

In [18]:
np.sum(x)

10

In [19]:
x = np.array([1,2,3,4,5,6])
x_reshaped = x.reshape(2,3)

In [23]:
x_reshaped

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
x_reshaped[1,1]

5

In [25]:
x_reshaped[1,1] = 100

In [26]:
x_reshaped

array([[  1,   2,   3],
       [  4, 100,   6]])

In [27]:
x

array([  1,   2,   3,   4, 100,   6])

In [28]:
x_reshaped.T

array([[  1,   4],
       [  2, 100],
       [  3,   6]])

In [30]:
np.sqrt(x)

array([ 1.        ,  1.41421356,  1.73205081,  2.        , 10.        ,
        2.44948974])

In [34]:
x =np.random.normal(size=10)

In [35]:
Y = x + np.random.normal(loc=10, scale=0.1, size=10)

In [36]:
Y

array([ 9.03084586,  9.43682774,  9.61145643,  9.2315693 ,  9.97988708,
       10.31860844, 11.05264167, 10.58813604, 10.5304976 ,  8.86786519])

In [37]:
np.corrcoef(x,Y)

array([[1.        , 0.99501303],
       [0.99501303, 1.        ]])

In [49]:
rng = np.random.default_rng(3)

In [44]:
y =rng.standard_normal(size=10)

In [45]:
np.mean(y)

-0.050726804572525805

In [50]:
X = rng.standard_normal((10, 3))

In [51]:
X

array([[ 2.04091912, -2.55566503,  0.41809885],
       [-0.56776961, -0.45264929, -0.21559716],
       [-2.01998613, -0.23193238, -0.86521308],
       [ 3.32299952,  0.22578661, -0.35263079],
       [-0.28128742, -0.66804635, -1.05515055],
       [-0.39080098,  0.48194539, -0.23855361],
       [ 0.9577587 , -0.19980213,  0.02425957],
       [ 1.54582085,  0.54510552, -0.50522874],
       [-0.18283897,  0.54052513,  1.93508803],
       [-0.26962033, -0.24355868,  1.0023136 ]])

In [52]:
X.mean(axis=0)

array([ 0.41551948, -0.25582912,  0.01473861])